### ISSUE TITLE
Actually remove the full directory tree from /tmp/bitshift

### ISSUE THREAD

**Issue by earwig** [earwig/bitshift#33]
Remove the full directory tree when you clone a repo, @sevko. Currently, after cloning `foo/bar`, we're left with `/tmp/bitshift/foo`.

**Comment by sevko** [comment]
This is partly intentional. `indexer.GitIndexer` and `indexer._GitCloner` are threaded and work asynchronously, meaning that the `_GitCloner` might clone several repositories before the `GitIndexer` manages to index one of them; if any repositories belonged to the same author, they'd all be removed after only one was indexed, which would cause problems later on. Anyway, adding a conditional to remove the full path only after one directory remains.

**Comment by earwig** [comment]
The main concern is that we could be left with a /tmp/bitshift full of a thousand empty directories (not good).
